version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - repo:/data
    ports:
      - "6379:6379"
volumes:
  redis: